### ISSUE TITLE
need help with gradle issue

### ISSUE THREAD

**Issue by PrabhaBharath** [twilio/twilio-video-app-android#211] opened 2021-05-03 11:46 UTC
![Screenshot (359)](https://user-images.githubusercontent.com/53730066/116871859-8da9f480-ac32-11eb-867f-17e2a18556e8.png)
i'm added git project as gradle but i'm not able to use twilio project classes. please help me with this issue

**Comment by Alton09** [comment] 2021-05-03 15:29
Hi @PrabhaBharath ! Thank you for reaching out. Do you mind adding more detail around what issue you are experiencing? If you could also add specific steps to reproduce the issue it would also be very helpful.

**Comment by PrabhaBharath** [comment] 2021-05-04 04:28
Hi @Alton09 ! Thanks for the response. I'm facing the issue after adding the project as dependency. i'm not able to access the twilio classes. i added project using this implementation project(path: ':twilio', configuration: 'default') .

**Comment by PrabhaBharath** [comment] 2021-05-04 04:31
if i added project using implementation project(path: ':twilio').
 i'm facing "Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'." this error.

**Comment by Alton09** [comment] 2021-05-04 15:31
@PrabhaBharath It looks like you are having issues setting up a Gradle module. Are you trying to reference this application as a separate module in your project? This is not something we support as part of this repository, as this is a standalone Android application.

**Comment by PrabhaBharath** [comment] 2021-05-05 12:41
thanks for the replay @Alton09

**Comment by Alton09** [comment] 2021-05-05 15:25
I'll close this issue for now. Feel free to open any additional issues as needed while working with this app. Thanks!

**Closed by Alton09** 2021-05-05 15:25 UTC
