### ISSUE TITLE
"Record participants on connect" not working from settings

### ISSUE THREAD

**Issue by asifrony** [twilio/twilio-video-app-android#209] opened 2021-04-30 06:26 UTC
Hi,
In settings > advanced there is a feature "Record participants on connect" which default value is false (unchecked in settings > advanced).
But still the video and audio is recording.
I need to turn off recording from app, not from Twillio console, is it possible?
I am in debugging/development state now, not in production.

Thanks,
Asif

**Comment by Alton09** [comment] 2021-04-30 15:30
Hi @asifrony ! Thanks for reaching out. This actually won't have an affect in the `community` flavor of the app, it only works on the Twilio internal flavor which is not exposed to devs outside of Twilio. This is indeed unexpected behavior and we will work on removing it from the `community` flavor of the app to avoid confusion. 

> I need to turn off recording from app, not from Twillio console, is it possible?

You can indeed control recording from the app, but you will have to write the logic to do so as it is not currently supported. In order to add this support in the app you will have to interact with the [Recording REST API](https://www.twilio.com/docs/video/api/recordings-resource) since there is no support for this in the Video Android SDK. Hope that helps!

**Comment by Alton09** [comment] 2021-05-04 15:33
Hi @asifrony ! I went ahead and merged #210 which fixes the settings issue that you mentioned. I'm going to close this issue for now but please reopen as needed. Thanks!

**Closed by Alton09** 2021-05-04 15:33 UTC
Labels: bug
